### PR TITLE
update examples

### PR DESCRIPTION
**Pull request by abdullahhamadeh**

### CODE REVIEW

**Comment by abdullahhamadeh** [comment]
Hi @Yuri05.  Can we merge this PR?

**Comment by Yuri05** [comment]
Hi Abdullah, the build fails due to the obsolete pandoc installation syntax.
Please replace `cinst pandoc` in 
https://github.com/Open-Systems-Pharmacology/OSPSuite.GlobalSensitivity/blob/3e61327113067ddf8410fe17158ee852c01e13e4/appveyor.yml#L13C9-L13C21
with `choco install pandoc`
(e.g. compare https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/blob/68a117aa087ab473330d6e1ed20e35fe00fb7c41/appveyor.yml#L13C9-L13C29)

**Comment by abdullahhamadeh** [comment]
Done, thanks,

**Review by Yuri05 — APPROVED** [review]

**Comment by Yuri05** [comment]
Looks good. merging

**Pull request merged**
